// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nttkglkhiiatocoowgaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50dGtnbGtoaWlhdG9jb293Z2FxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMTE4ODQsImV4cCI6MjA2MTU4Nzg4NH0.6hBbki5ZTvj8mEU7Dc5taFUuXQ76Q7KE9S4es12NfZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);